spring.application.name=Fashion_News_App

# DB Info
spring.datasource.url=jdbc:mysql://localhost:3306/FashionNews
spring.datasource.username=root
spring.datasource.password=sho09214

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Server Info
server.port=8080

# JWT
jwt.secret=VGVzdFNlY3JldEtleUZvckpXVF9TdXBlcl9Mb25nXzMyX0J5dGVz
jwt.expiration=86400000

# Log
logging.level.root=INFO
logging.level.com.example.Fashion_News_App=DEBUG

# URL
rss.sources.fashionsnap=https://www.fashionsnap.com/rss.xml
rss.sources.wwdjapan=https://www.wwdjapan.com/feed

# ????
rss.fetch.delay-ms=200